
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/games-shelf
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: true